### ISSUE TITLE
dapr  fail to init Kubernetes in limited network

### ISSUE THREAD

**Issue by shaibarlev** [dapr/installer-bundle#4] opened 2022-04-06 19:37 UTC
I used the new installer-bundle and download the bits , extract the bits and called :dapr init for self hosting , and its worked fine , thank you.
Now I wanted to  : dapr init -k it on my local Kubernetes (Tanzu by VMWare)  and getting this errors:

dapr init -k
Making the jump to hyperspace...
Note: To install Dapr using Helm, see here: https://docs.dapr.io/getting-started/install-dapr-kubernetes/#install-with-helm-advanced

Deploying the Dapr control plane to your cluster...
looks like "https://dapr.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get "https://dapr.github.io/helm-charts/index.yaml": dial tcp 185.199.108.153:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

1. Is there a way to get the Helm-charts Locally ? 
2.  Can this be part of the installer-bundle ? 
3.  How can init dapr control plane on Kubernetes , from local files on local Helm Repository ?

Hope there is easy solution ?

**Comment by shaibarlev** [comment] 2022-04-08 13:52
Merge this to 
[https://github.com/dapr/cli/pull/895#issue-1139602197](url)

**Comment by shaibarlev** [comment] 2022-04-08 13:53
Duplicate of #https://github.com/dapr/cli/pull/895#issue-1139602197

**Comment by mukundansundar** [comment] 2022-04-08 20:27
> Duplicate of #[dapr/cli#895 (comment)](https://github.com/dapr/cli/pull/895#issue-1139602197)

@shaibarlev That PR has been triaged for 1.8 release ...

**Comment by shaibarlev** [comment] 2022-04-09 21:43
Thanks @mukundansundar .
Is there a workaround to make this work via manual steps now , before its hit 1.8 ?

**Comment by shivamkm07** [comment] 2022-06-28 14:31
Duplicate of https://github.com/dapr/installer-bundle/issues/8#issuecomment-1168801047

**Comment by shivamkm07** [comment] 2023-01-24 04:44
Closing due to no activity

**Closed by shivamkm07** 2023-01-24 04:44 UTC
